# @package _group_

name: 'BCA'
robot: 'panda,ur5_blind'

time_in_state: False


activation: lrelu
lr: 0.0005
weight_decay: 0.000001
grad_clip: 0.1
demo_augmentation: True
demo_augmentation_every_n: 10

floating_viewpoint_env_bounds: [1.3,20,-135, 1.3,60,135] 
floating_viewpoint_agent_bounds: [1.3,20,-135, 1.3,60,135] 
floating_viewpoint_resolution: [0.05,10.0,10.0] 

low_dim_size: 17
floating_cam: True   # True  False  
