# @package _group_

name: 'LENS'

lr: 0.0005
tau: 0.0025

activation: lrelu
norm: None

random_viewpoint: False  # 

floating_cam: True   # True  False  

reach_reward: 0.02

use_aux_rewards: True

viewpoint_augmentation: True

use_vae: False

time_in_state: False

viewpoint_align: True

robot: 'panda,ur5_blind'

low_dim_size: 12

lambda_weight_l2: 0.000001
lambda_trans_qreg: 1.0
lambda_rot_qreg: 1.0

rotation_resolution: 5  
# r,theta,phi  
arm_viewpoint_env_bounds: [0.65,45,-45,  0.65,45,45] #[0.1,20,-90, 0.5,60,90]
arm_viewpoint_agent_bounds: [0.65,45,-90,  0.65,45,90] #[0.1,20,-90, 0.5,60,90]
arm_viewpoint_resolution: [0.05,5.0,5.0]

# r,theta,phi  
floating_viewpoint_env_bounds: [1.3,20,-135, 1.3,60,135] 
floating_viewpoint_agent_bounds: [1.3,20,-135, 1.3,60,135] 
floating_viewpoint_resolution: [0.05,10.0,10.0] 

# Voxel
image_crop_size: 64
bounds_offset: [0.15]
voxel_sizes: [16, 16] 

crop_augmentation: True

demo_augmentation: True
demo_augmentation_every_n: 10
exploration_strategy: gaussian

# LENS-specific additions
target_object_id: 211
camera_exploration_steps: 5
R_vis_weight: 0.02
R_struct_weight: 0.01
P_smooth_weight: 0.005

# SAC parameters (copied from SAC.yaml)
critic_lr: 0.001
actor_lr: 0.001
critic_weight_decay: 0.000001
actor_weight_decay: 0.000001
critic_grad_clip: 5
actor_grad_clip: 5
decoder_weight_decay: 0.000001
decoder_grad_clip: 5
decoder_lr: 0.001
decoder_latent_lambda: 0.000001
encoder_tau: 0.05
alpha: 1.0
alpha_auto_tune: True
alpha_lr: 0.0005